/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ArchitectureProject {
  'id' : string,
  'title' : string,
  'completedYear' : bigint,
  'featured' : boolean,
  'architectName' : string,
  'projectType' : ProjectType,
  'owner' : Principal,
  'description' : string,
  'imageUrl' : ExternalBlob,
  'location' : string,
}
export interface ConstructionEstimate {
  'id' : string,
  'foundationCost' : bigint,
  'projectName' : string,
  'projectType' : ProjectType,
  'owner' : Principal,
  'plumbingCost' : bigint,
  'totalArea' : bigint,
  'totalCost' : bigint,
  'flooringCost' : bigint,
  'finishingCost' : bigint,
  'roofingCost' : bigint,
  'notes' : string,
  'electricalCost' : bigint,
  'structureCost' : bigint,
}
export type ExternalBlob = Uint8Array;
export interface FloorPlan {
  'id' : string,
  'title' : string,
  'owner' : Principal,
  'floors' : bigint,
  'authorName' : string,
  'totalArea' : bigint,
  'description' : string,
  'style' : FloorStyle,
  'imageUrl' : ExternalBlob,
  'bathrooms' : bigint,
  'price' : bigint,
  'rooms' : bigint,
}
export type FloorStyle = { 'traditional' : null } |
  { 'modern' : null } |
  { 'contemporary' : null };
export type ListingStatus = { 'rented' : null } |
  { 'active' : null } |
  { 'sold' : null };
export type ListingType = { 'buy' : null } |
  { 'rent' : null } |
  { 'sell' : null };
export type ProjectType = { 'interior' : null } |
  { 'commercial' : null } |
  { 'residential' : null };
export interface PropertyListing {
  'id' : string,
  'status' : ListingStatus,
  'title' : string,
  'contactName' : string,
  'propertyType' : PropertyType,
  'bedrooms' : bigint,
  'owner' : Principal,
  'area' : bigint,
  'description' : string,
  'listingType' : ListingType,
  'bathrooms' : bigint,
  'price' : bigint,
  'location' : string,
  'contactPhone' : string,
}
export type PropertyType = { 'commercial' : null } |
  { 'plot' : null } |
  { 'residential' : null };
export interface UserProfile {
  'name' : string,
  'role' : string,
  'email' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'adminDeleteFloorPlan' : ActorMethod<[string], undefined>,
  'adminDeleteListing' : ActorMethod<[string], undefined>,
  'adminDeleteProject' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'browseArchitectureProjects' : ActorMethod<[], Array<ArchitectureProject>>,
  'browseFloorPlans' : ActorMethod<[], Array<FloorPlan>>,
  'browsePropertyListings' : ActorMethod<[], Array<PropertyListing>>,
  'createArchitectureProject' : ActorMethod<[ArchitectureProject], undefined>,
  'createFloorPlan' : ActorMethod<[FloorPlan], undefined>,
  'createPropertyListing' : ActorMethod<[PropertyListing], undefined>,
  'deleteArchitectureProject' : ActorMethod<[string], undefined>,
  'deleteConstructionEstimate' : ActorMethod<[string], undefined>,
  'deleteFloorPlan' : ActorMethod<[string], undefined>,
  'deletePropertyListing' : ActorMethod<[string], undefined>,
  'filterListingsByType' : ActorMethod<[ListingType], Array<PropertyListing>>,
  'getArchitectureProject' : ActorMethod<[string], ArchitectureProject>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getConstructionEstimate' : ActorMethod<[string], ConstructionEstimate>,
  'getFloorPlan' : ActorMethod<[string], FloorPlan>,
  'getPropertyListing' : ActorMethod<[string], PropertyListing>,
  'getUserEstimates' : ActorMethod<[Principal], Array<ConstructionEstimate>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveConstructionEstimate' : ActorMethod<[ConstructionEstimate], undefined>,
  'updateArchitectureProject' : ActorMethod<
    [string, ArchitectureProject],
    undefined
  >,
  'updateConstructionEstimate' : ActorMethod<
    [string, ConstructionEstimate],
    undefined
  >,
  'updateFloorPlan' : ActorMethod<[string, FloorPlan], undefined>,
  'updatePropertyListing' : ActorMethod<[string, PropertyListing], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];