/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ProjectType = IDL.Variant({
  'interior' : IDL.Null,
  'commercial' : IDL.Null,
  'residential' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const ArchitectureProject = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'completedYear' : IDL.Nat,
  'featured' : IDL.Bool,
  'architectName' : IDL.Text,
  'projectType' : ProjectType,
  'owner' : IDL.Principal,
  'description' : IDL.Text,
  'imageUrl' : ExternalBlob,
  'location' : IDL.Text,
});
export const FloorStyle = IDL.Variant({
  'traditional' : IDL.Null,
  'modern' : IDL.Null,
  'contemporary' : IDL.Null,
});
export const FloorPlan = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'owner' : IDL.Principal,
  'floors' : IDL.Nat,
  'authorName' : IDL.Text,
  'totalArea' : IDL.Nat,
  'description' : IDL.Text,
  'style' : FloorStyle,
  'imageUrl' : ExternalBlob,
  'bathrooms' : IDL.Nat,
  'price' : IDL.Nat,
  'rooms' : IDL.Nat,
});
export const ListingStatus = IDL.Variant({
  'rented' : IDL.Null,
  'active' : IDL.Null,
  'sold' : IDL.Null,
});
export const PropertyType = IDL.Variant({
  'commercial' : IDL.Null,
  'plot' : IDL.Null,
  'residential' : IDL.Null,
});
export const ListingType = IDL.Variant({
  'buy' : IDL.Null,
  'rent' : IDL.Null,
  'sell' : IDL.Null,
});
export const PropertyListing = IDL.Record({
  'id' : IDL.Text,
  'status' : ListingStatus,
  'title' : IDL.Text,
  'contactName' : IDL.Text,
  'propertyType' : PropertyType,
  'bedrooms' : IDL.Nat,
  'owner' : IDL.Principal,
  'area' : IDL.Nat,
  'description' : IDL.Text,
  'listingType' : ListingType,
  'bathrooms' : IDL.Nat,
  'price' : IDL.Nat,
  'location' : IDL.Text,
  'contactPhone' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'role' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const ConstructionEstimate = IDL.Record({
  'id' : IDL.Text,
  'foundationCost' : IDL.Nat,
  'projectName' : IDL.Text,
  'projectType' : ProjectType,
  'owner' : IDL.Principal,
  'plumbingCost' : IDL.Nat,
  'totalArea' : IDL.Nat,
  'totalCost' : IDL.Nat,
  'flooringCost' : IDL.Nat,
  'finishingCost' : IDL.Nat,
  'roofingCost' : IDL.Nat,
  'notes' : IDL.Text,
  'electricalCost' : IDL.Nat,
  'structureCost' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'adminDeleteFloorPlan' : IDL.Func([IDL.Text], [], []),
  'adminDeleteListing' : IDL.Func([IDL.Text], [], []),
  'adminDeleteProject' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'browseArchitectureProjects' : IDL.Func(
      [],
      [IDL.Vec(ArchitectureProject)],
      ['query'],
    ),
  'browseFloorPlans' : IDL.Func([], [IDL.Vec(FloorPlan)], ['query']),
  'browsePropertyListings' : IDL.Func(
      [],
      [IDL.Vec(PropertyListing)],
      ['query'],
    ),
  'createArchitectureProject' : IDL.Func([ArchitectureProject], [], []),
  'createFloorPlan' : IDL.Func([FloorPlan], [], []),
  'createPropertyListing' : IDL.Func([PropertyListing], [], []),
  'deleteArchitectureProject' : IDL.Func([IDL.Text], [], []),
  'deleteConstructionEstimate' : IDL.Func([IDL.Text], [], []),
  'deleteFloorPlan' : IDL.Func([IDL.Text], [], []),
  'deletePropertyListing' : IDL.Func([IDL.Text], [], []),
  'filterListingsByType' : IDL.Func(
      [ListingType],
      [IDL.Vec(PropertyListing)],
      ['query'],
    ),
  'getArchitectureProject' : IDL.Func(
      [IDL.Text],
      [ArchitectureProject],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getConstructionEstimate' : IDL.Func(
      [IDL.Text],
      [ConstructionEstimate],
      ['query'],
    ),
  'getFloorPlan' : IDL.Func([IDL.Text], [FloorPlan], ['query']),
  'getPropertyListing' : IDL.Func([IDL.Text], [PropertyListing], ['query']),
  'getUserEstimates' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(ConstructionEstimate)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveConstructionEstimate' : IDL.Func([ConstructionEstimate], [], []),
  'updateArchitectureProject' : IDL.Func(
      [IDL.Text, ArchitectureProject],
      [],
      [],
    ),
  'updateConstructionEstimate' : IDL.Func(
      [IDL.Text, ConstructionEstimate],
      [],
      [],
    ),
  'updateFloorPlan' : IDL.Func([IDL.Text, FloorPlan], [], []),
  'updatePropertyListing' : IDL.Func([IDL.Text, PropertyListing], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ProjectType = IDL.Variant({
    'interior' : IDL.Null,
    'commercial' : IDL.Null,
    'residential' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const ArchitectureProject = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'completedYear' : IDL.Nat,
    'featured' : IDL.Bool,
    'architectName' : IDL.Text,
    'projectType' : ProjectType,
    'owner' : IDL.Principal,
    'description' : IDL.Text,
    'imageUrl' : ExternalBlob,
    'location' : IDL.Text,
  });
  const FloorStyle = IDL.Variant({
    'traditional' : IDL.Null,
    'modern' : IDL.Null,
    'contemporary' : IDL.Null,
  });
  const FloorPlan = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'owner' : IDL.Principal,
    'floors' : IDL.Nat,
    'authorName' : IDL.Text,
    'totalArea' : IDL.Nat,
    'description' : IDL.Text,
    'style' : FloorStyle,
    'imageUrl' : ExternalBlob,
    'bathrooms' : IDL.Nat,
    'price' : IDL.Nat,
    'rooms' : IDL.Nat,
  });
  const ListingStatus = IDL.Variant({
    'rented' : IDL.Null,
    'active' : IDL.Null,
    'sold' : IDL.Null,
  });
  const PropertyType = IDL.Variant({
    'commercial' : IDL.Null,
    'plot' : IDL.Null,
    'residential' : IDL.Null,
  });
  const ListingType = IDL.Variant({
    'buy' : IDL.Null,
    'rent' : IDL.Null,
    'sell' : IDL.Null,
  });
  const PropertyListing = IDL.Record({
    'id' : IDL.Text,
    'status' : ListingStatus,
    'title' : IDL.Text,
    'contactName' : IDL.Text,
    'propertyType' : PropertyType,
    'bedrooms' : IDL.Nat,
    'owner' : IDL.Principal,
    'area' : IDL.Nat,
    'description' : IDL.Text,
    'listingType' : ListingType,
    'bathrooms' : IDL.Nat,
    'price' : IDL.Nat,
    'location' : IDL.Text,
    'contactPhone' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'role' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const ConstructionEstimate = IDL.Record({
    'id' : IDL.Text,
    'foundationCost' : IDL.Nat,
    'projectName' : IDL.Text,
    'projectType' : ProjectType,
    'owner' : IDL.Principal,
    'plumbingCost' : IDL.Nat,
    'totalArea' : IDL.Nat,
    'totalCost' : IDL.Nat,
    'flooringCost' : IDL.Nat,
    'finishingCost' : IDL.Nat,
    'roofingCost' : IDL.Nat,
    'notes' : IDL.Text,
    'electricalCost' : IDL.Nat,
    'structureCost' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'adminDeleteFloorPlan' : IDL.Func([IDL.Text], [], []),
    'adminDeleteListing' : IDL.Func([IDL.Text], [], []),
    'adminDeleteProject' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'browseArchitectureProjects' : IDL.Func(
        [],
        [IDL.Vec(ArchitectureProject)],
        ['query'],
      ),
    'browseFloorPlans' : IDL.Func([], [IDL.Vec(FloorPlan)], ['query']),
    'browsePropertyListings' : IDL.Func(
        [],
        [IDL.Vec(PropertyListing)],
        ['query'],
      ),
    'createArchitectureProject' : IDL.Func([ArchitectureProject], [], []),
    'createFloorPlan' : IDL.Func([FloorPlan], [], []),
    'createPropertyListing' : IDL.Func([PropertyListing], [], []),
    'deleteArchitectureProject' : IDL.Func([IDL.Text], [], []),
    'deleteConstructionEstimate' : IDL.Func([IDL.Text], [], []),
    'deleteFloorPlan' : IDL.Func([IDL.Text], [], []),
    'deletePropertyListing' : IDL.Func([IDL.Text], [], []),
    'filterListingsByType' : IDL.Func(
        [ListingType],
        [IDL.Vec(PropertyListing)],
        ['query'],
      ),
    'getArchitectureProject' : IDL.Func(
        [IDL.Text],
        [ArchitectureProject],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getConstructionEstimate' : IDL.Func(
        [IDL.Text],
        [ConstructionEstimate],
        ['query'],
      ),
    'getFloorPlan' : IDL.Func([IDL.Text], [FloorPlan], ['query']),
    'getPropertyListing' : IDL.Func([IDL.Text], [PropertyListing], ['query']),
    'getUserEstimates' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(ConstructionEstimate)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveConstructionEstimate' : IDL.Func([ConstructionEstimate], [], []),
    'updateArchitectureProject' : IDL.Func(
        [IDL.Text, ArchitectureProject],
        [],
        [],
      ),
    'updateConstructionEstimate' : IDL.Func(
        [IDL.Text, ConstructionEstimate],
        [],
        [],
      ),
    'updateFloorPlan' : IDL.Func([IDL.Text, FloorPlan], [], []),
    'updatePropertyListing' : IDL.Func([IDL.Text, PropertyListing], [], []),
  });
};

export const init = ({ IDL }) => { return []; };