/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface FloorPlan {
    id: string;
    title: string;
    owner: Principal;
    floors: bigint;
    authorName: string;
    totalArea: bigint;
    description: string;
    style: FloorStyle;
    imageUrl: ExternalBlob;
    bathrooms: bigint;
    price: bigint;
    rooms: bigint;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface ConstructionEstimate {
    id: string;
    foundationCost: bigint;
    projectName: string;
    projectType: ProjectType;
    owner: Principal;
    plumbingCost: bigint;
    totalArea: bigint;
    totalCost: bigint;
    flooringCost: bigint;
    finishingCost: bigint;
    roofingCost: bigint;
    notes: string;
    electricalCost: bigint;
    structureCost: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface PropertyListing {
    id: string;
    status: ListingStatus;
    title: string;
    contactName: string;
    propertyType: PropertyType;
    bedrooms: bigint;
    owner: Principal;
    area: bigint;
    description: string;
    listingType: ListingType;
    bathrooms: bigint;
    price: bigint;
    location: string;
    contactPhone: string;
}
export interface ArchitectureProject {
    id: string;
    title: string;
    completedYear: bigint;
    featured: boolean;
    architectName: string;
    projectType: ProjectType;
    owner: Principal;
    description: string;
    imageUrl: ExternalBlob;
    location: string;
}
export interface UserProfile {
    name: string;
    role: string;
    email: string;
    phone: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum FloorStyle {
    traditional = "traditional",
    modern = "modern",
    contemporary = "contemporary"
}
export enum ListingStatus {
    rented = "rented",
    active = "active",
    sold = "sold"
}
export enum ListingType {
    buy = "buy",
    rent = "rent",
    sell = "sell"
}
export enum ProjectType {
    interior = "interior",
    commercial = "commercial",
    residential = "residential"
}
export enum PropertyType {
    commercial = "commercial",
    plot = "plot",
    residential = "residential"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    adminDeleteFloorPlan(id: string): Promise<void>;
    adminDeleteListing(id: string): Promise<void>;
    adminDeleteProject(id: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    browseArchitectureProjects(): Promise<Array<ArchitectureProject>>;
    browseFloorPlans(): Promise<Array<FloorPlan>>;
    browsePropertyListings(): Promise<Array<PropertyListing>>;
    createArchitectureProject(project: ArchitectureProject): Promise<void>;
    createFloorPlan(plan: FloorPlan): Promise<void>;
    createPropertyListing(listing: PropertyListing): Promise<void>;
    deleteArchitectureProject(id: string): Promise<void>;
    deleteConstructionEstimate(id: string): Promise<void>;
    deleteFloorPlan(id: string): Promise<void>;
    deletePropertyListing(id: string): Promise<void>;
    filterListingsByType(listingType: ListingType): Promise<Array<PropertyListing>>;
    getArchitectureProject(id: string): Promise<ArchitectureProject>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getConstructionEstimate(id: string): Promise<ConstructionEstimate>;
    getFloorPlan(id: string): Promise<FloorPlan>;
    getPropertyListing(id: string): Promise<PropertyListing>;
    getUserEstimates(user: Principal): Promise<Array<ConstructionEstimate>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveConstructionEstimate(estimate: ConstructionEstimate): Promise<void>;
    updateArchitectureProject(id: string, updatedProject: ArchitectureProject): Promise<void>;
    updateConstructionEstimate(id: string, updatedEstimate: ConstructionEstimate): Promise<void>;
    updateFloorPlan(id: string, updatedPlan: FloorPlan): Promise<void>;
    updatePropertyListing(id: string, updatedListing: PropertyListing): Promise<void>;
}
import type { ArchitectureProject as _ArchitectureProject, ConstructionEstimate as _ConstructionEstimate, ExternalBlob as _ExternalBlob, FloorPlan as _FloorPlan, FloorStyle as _FloorStyle, ListingStatus as _ListingStatus, ListingType as _ListingType, ProjectType as _ProjectType, PropertyListing as _PropertyListing, PropertyType as _PropertyType, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async adminDeleteFloorPlan(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminDeleteFloorPlan(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminDeleteFloorPlan(arg0);
            return result;
        }
    }
    async adminDeleteListing(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminDeleteListing(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminDeleteListing(arg0);
            return result;
        }
    }
    async adminDeleteProject(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminDeleteProject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminDeleteProject(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async browseArchitectureProjects(): Promise<Array<ArchitectureProject>> {
        if (this.processError) {
            try {
                const result = await this.actor.browseArchitectureProjects();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.browseArchitectureProjects();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async browseFloorPlans(): Promise<Array<FloorPlan>> {
        if (this.processError) {
            try {
                const result = await this.actor.browseFloorPlans();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.browseFloorPlans();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async browsePropertyListings(): Promise<Array<PropertyListing>> {
        if (this.processError) {
            try {
                const result = await this.actor.browsePropertyListings();
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.browsePropertyListings();
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async createArchitectureProject(arg0: ArchitectureProject): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createArchitectureProject(await to_candid_ArchitectureProject_n30(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createArchitectureProject(await to_candid_ArchitectureProject_n30(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createFloorPlan(arg0: FloorPlan): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createFloorPlan(await to_candid_FloorPlan_n35(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createFloorPlan(await to_candid_FloorPlan_n35(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createPropertyListing(arg0: PropertyListing): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createPropertyListing(to_candid_PropertyListing_n39(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPropertyListing(to_candid_PropertyListing_n39(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deleteArchitectureProject(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteArchitectureProject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteArchitectureProject(arg0);
            return result;
        }
    }
    async deleteConstructionEstimate(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteConstructionEstimate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteConstructionEstimate(arg0);
            return result;
        }
    }
    async deleteFloorPlan(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteFloorPlan(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteFloorPlan(arg0);
            return result;
        }
    }
    async deletePropertyListing(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePropertyListing(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePropertyListing(arg0);
            return result;
        }
    }
    async filterListingsByType(arg0: ListingType): Promise<Array<PropertyListing>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterListingsByType(to_candid_ListingType_n45(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterListingsByType(to_candid_ListingType_n45(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getArchitectureProject(arg0: string): Promise<ArchitectureProject> {
        if (this.processError) {
            try {
                const result = await this.actor.getArchitectureProject(arg0);
                return from_candid_ArchitectureProject_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getArchitectureProject(arg0);
            return from_candid_ArchitectureProject_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async getConstructionEstimate(arg0: string): Promise<ConstructionEstimate> {
        if (this.processError) {
            try {
                const result = await this.actor.getConstructionEstimate(arg0);
                return from_candid_ConstructionEstimate_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getConstructionEstimate(arg0);
            return from_candid_ConstructionEstimate_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFloorPlan(arg0: string): Promise<FloorPlan> {
        if (this.processError) {
            try {
                const result = await this.actor.getFloorPlan(arg0);
                return from_candid_FloorPlan_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFloorPlan(arg0);
            return from_candid_FloorPlan_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPropertyListing(arg0: string): Promise<PropertyListing> {
        if (this.processError) {
            try {
                const result = await this.actor.getPropertyListing(arg0);
                return from_candid_PropertyListing_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPropertyListing(arg0);
            return from_candid_PropertyListing_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserEstimates(arg0: Principal): Promise<Array<ConstructionEstimate>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserEstimates(arg0);
                return from_candid_vec_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserEstimates(arg0);
            return from_candid_vec_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async saveConstructionEstimate(arg0: ConstructionEstimate): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveConstructionEstimate(to_candid_ConstructionEstimate_n53(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveConstructionEstimate(to_candid_ConstructionEstimate_n53(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateArchitectureProject(arg0: string, arg1: ArchitectureProject): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateArchitectureProject(arg0, await to_candid_ArchitectureProject_n30(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateArchitectureProject(arg0, await to_candid_ArchitectureProject_n30(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateConstructionEstimate(arg0: string, arg1: ConstructionEstimate): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateConstructionEstimate(arg0, to_candid_ConstructionEstimate_n53(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateConstructionEstimate(arg0, to_candid_ConstructionEstimate_n53(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateFloorPlan(arg0: string, arg1: FloorPlan): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateFloorPlan(arg0, await to_candid_FloorPlan_n35(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateFloorPlan(arg0, await to_candid_FloorPlan_n35(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updatePropertyListing(arg0: string, arg1: PropertyListing): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePropertyListing(arg0, to_candid_PropertyListing_n39(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePropertyListing(arg0, to_candid_PropertyListing_n39(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
async function from_candid_ArchitectureProject_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ArchitectureProject): Promise<ArchitectureProject> {
    return await from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_ConstructionEstimate_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ConstructionEstimate): ConstructionEstimate {
    return from_candid_record_n51(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
async function from_candid_FloorPlan_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FloorPlan): Promise<FloorPlan> {
    return await from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_FloorStyle_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FloorStyle): FloorStyle {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_ListingStatus_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ListingStatus): ListingStatus {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid_ListingType_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ListingType): ListingType {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_ProjectType_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProjectType): ProjectType {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_PropertyListing_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PropertyListing): PropertyListing {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_PropertyType_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PropertyType): PropertyType {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n49(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    completedYear: bigint;
    featured: boolean;
    architectName: string;
    projectType: _ProjectType;
    owner: Principal;
    description: string;
    imageUrl: _ExternalBlob;
    location: string;
}): Promise<{
    id: string;
    title: string;
    completedYear: bigint;
    featured: boolean;
    architectName: string;
    projectType: ProjectType;
    owner: Principal;
    description: string;
    imageUrl: ExternalBlob;
    location: string;
}> {
    return {
        id: value.id,
        title: value.title,
        completedYear: value.completedYear,
        featured: value.featured,
        architectName: value.architectName,
        projectType: from_candid_ProjectType_n13(_uploadFile, _downloadFile, value.projectType),
        owner: value.owner,
        description: value.description,
        imageUrl: await from_candid_ExternalBlob_n15(_uploadFile, _downloadFile, value.imageUrl),
        location: value.location
    };
}
async function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    owner: Principal;
    floors: bigint;
    authorName: string;
    totalArea: bigint;
    description: string;
    style: _FloorStyle;
    imageUrl: _ExternalBlob;
    bathrooms: bigint;
    price: bigint;
    rooms: bigint;
}): Promise<{
    id: string;
    title: string;
    owner: Principal;
    floors: bigint;
    authorName: string;
    totalArea: bigint;
    description: string;
    style: FloorStyle;
    imageUrl: ExternalBlob;
    bathrooms: bigint;
    price: bigint;
    rooms: bigint;
}> {
    return {
        id: value.id,
        title: value.title,
        owner: value.owner,
        floors: value.floors,
        authorName: value.authorName,
        totalArea: value.totalArea,
        description: value.description,
        style: from_candid_FloorStyle_n19(_uploadFile, _downloadFile, value.style),
        imageUrl: await from_candid_ExternalBlob_n15(_uploadFile, _downloadFile, value.imageUrl),
        bathrooms: value.bathrooms,
        price: value.price,
        rooms: value.rooms
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _ListingStatus;
    title: string;
    contactName: string;
    propertyType: _PropertyType;
    bedrooms: bigint;
    owner: Principal;
    area: bigint;
    description: string;
    listingType: _ListingType;
    bathrooms: bigint;
    price: bigint;
    location: string;
    contactPhone: string;
}): {
    id: string;
    status: ListingStatus;
    title: string;
    contactName: string;
    propertyType: PropertyType;
    bedrooms: bigint;
    owner: Principal;
    area: bigint;
    description: string;
    listingType: ListingType;
    bathrooms: bigint;
    price: bigint;
    location: string;
    contactPhone: string;
} {
    return {
        id: value.id,
        status: from_candid_ListingStatus_n24(_uploadFile, _downloadFile, value.status),
        title: value.title,
        contactName: value.contactName,
        propertyType: from_candid_PropertyType_n26(_uploadFile, _downloadFile, value.propertyType),
        bedrooms: value.bedrooms,
        owner: value.owner,
        area: value.area,
        description: value.description,
        listingType: from_candid_ListingType_n28(_uploadFile, _downloadFile, value.listingType),
        bathrooms: value.bathrooms,
        price: value.price,
        location: value.location,
        contactPhone: value.contactPhone
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    foundationCost: bigint;
    projectName: string;
    projectType: _ProjectType;
    owner: Principal;
    plumbingCost: bigint;
    totalArea: bigint;
    totalCost: bigint;
    flooringCost: bigint;
    finishingCost: bigint;
    roofingCost: bigint;
    notes: string;
    electricalCost: bigint;
    structureCost: bigint;
}): {
    id: string;
    foundationCost: bigint;
    projectName: string;
    projectType: ProjectType;
    owner: Principal;
    plumbingCost: bigint;
    totalArea: bigint;
    totalCost: bigint;
    flooringCost: bigint;
    finishingCost: bigint;
    roofingCost: bigint;
    notes: string;
    electricalCost: bigint;
    structureCost: bigint;
} {
    return {
        id: value.id,
        foundationCost: value.foundationCost,
        projectName: value.projectName,
        projectType: from_candid_ProjectType_n13(_uploadFile, _downloadFile, value.projectType),
        owner: value.owner,
        plumbingCost: value.plumbingCost,
        totalArea: value.totalArea,
        totalCost: value.totalCost,
        flooringCost: value.flooringCost,
        finishingCost: value.finishingCost,
        roofingCost: value.roofingCost,
        notes: value.notes,
        electricalCost: value.electricalCost,
        structureCost: value.structureCost
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    interior: null;
} | {
    commercial: null;
} | {
    residential: null;
}): ProjectType {
    return "interior" in value ? ProjectType.interior : "commercial" in value ? ProjectType.commercial : "residential" in value ? ProjectType.residential : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    traditional: null;
} | {
    modern: null;
} | {
    contemporary: null;
}): FloorStyle {
    return "traditional" in value ? FloorStyle.traditional : "modern" in value ? FloorStyle.modern : "contemporary" in value ? FloorStyle.contemporary : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    rented: null;
} | {
    active: null;
} | {
    sold: null;
}): ListingStatus {
    return "rented" in value ? ListingStatus.rented : "active" in value ? ListingStatus.active : "sold" in value ? ListingStatus.sold : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    commercial: null;
} | {
    plot: null;
} | {
    residential: null;
}): PropertyType {
    return "commercial" in value ? PropertyType.commercial : "plot" in value ? PropertyType.plot : "residential" in value ? PropertyType.residential : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    buy: null;
} | {
    rent: null;
} | {
    sell: null;
}): ListingType {
    return "buy" in value ? ListingType.buy : "rent" in value ? ListingType.rent : "sell" in value ? ListingType.sell : value;
}
function from_candid_variant_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
async function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ArchitectureProject>): Promise<Array<ArchitectureProject>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ArchitectureProject_n11(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FloorPlan>): Promise<Array<FloorPlan>> {
    return await Promise.all(value.map(async (x)=>await from_candid_FloorPlan_n17(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PropertyListing>): Array<PropertyListing> {
    return value.map((x)=>from_candid_PropertyListing_n22(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ConstructionEstimate>): Array<ConstructionEstimate> {
    return value.map((x)=>from_candid_ConstructionEstimate_n50(_uploadFile, _downloadFile, x));
}
async function to_candid_ArchitectureProject_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ArchitectureProject): Promise<_ArchitectureProject> {
    return await to_candid_record_n31(_uploadFile, _downloadFile, value);
}
function to_candid_ConstructionEstimate_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ConstructionEstimate): _ConstructionEstimate {
    return to_candid_record_n54(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
async function to_candid_FloorPlan_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FloorPlan): Promise<_FloorPlan> {
    return await to_candid_record_n36(_uploadFile, _downloadFile, value);
}
function to_candid_FloorStyle_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FloorStyle): _FloorStyle {
    return to_candid_variant_n38(_uploadFile, _downloadFile, value);
}
function to_candid_ListingStatus_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ListingStatus): _ListingStatus {
    return to_candid_variant_n42(_uploadFile, _downloadFile, value);
}
function to_candid_ListingType_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ListingType): _ListingType {
    return to_candid_variant_n46(_uploadFile, _downloadFile, value);
}
function to_candid_ProjectType_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProjectType): _ProjectType {
    return to_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function to_candid_PropertyListing_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PropertyListing): _PropertyListing {
    return to_candid_record_n40(_uploadFile, _downloadFile, value);
}
function to_candid_PropertyType_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PropertyType): _PropertyType {
    return to_candid_variant_n44(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    completedYear: bigint;
    featured: boolean;
    architectName: string;
    projectType: ProjectType;
    owner: Principal;
    description: string;
    imageUrl: ExternalBlob;
    location: string;
}): Promise<{
    id: string;
    title: string;
    completedYear: bigint;
    featured: boolean;
    architectName: string;
    projectType: _ProjectType;
    owner: Principal;
    description: string;
    imageUrl: _ExternalBlob;
    location: string;
}> {
    return {
        id: value.id,
        title: value.title,
        completedYear: value.completedYear,
        featured: value.featured,
        architectName: value.architectName,
        projectType: to_candid_ProjectType_n32(_uploadFile, _downloadFile, value.projectType),
        owner: value.owner,
        description: value.description,
        imageUrl: await to_candid_ExternalBlob_n34(_uploadFile, _downloadFile, value.imageUrl),
        location: value.location
    };
}
async function to_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    owner: Principal;
    floors: bigint;
    authorName: string;
    totalArea: bigint;
    description: string;
    style: FloorStyle;
    imageUrl: ExternalBlob;
    bathrooms: bigint;
    price: bigint;
    rooms: bigint;
}): Promise<{
    id: string;
    title: string;
    owner: Principal;
    floors: bigint;
    authorName: string;
    totalArea: bigint;
    description: string;
    style: _FloorStyle;
    imageUrl: _ExternalBlob;
    bathrooms: bigint;
    price: bigint;
    rooms: bigint;
}> {
    return {
        id: value.id,
        title: value.title,
        owner: value.owner,
        floors: value.floors,
        authorName: value.authorName,
        totalArea: value.totalArea,
        description: value.description,
        style: to_candid_FloorStyle_n37(_uploadFile, _downloadFile, value.style),
        imageUrl: await to_candid_ExternalBlob_n34(_uploadFile, _downloadFile, value.imageUrl),
        bathrooms: value.bathrooms,
        price: value.price,
        rooms: value.rooms
    };
}
function to_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: ListingStatus;
    title: string;
    contactName: string;
    propertyType: PropertyType;
    bedrooms: bigint;
    owner: Principal;
    area: bigint;
    description: string;
    listingType: ListingType;
    bathrooms: bigint;
    price: bigint;
    location: string;
    contactPhone: string;
}): {
    id: string;
    status: _ListingStatus;
    title: string;
    contactName: string;
    propertyType: _PropertyType;
    bedrooms: bigint;
    owner: Principal;
    area: bigint;
    description: string;
    listingType: _ListingType;
    bathrooms: bigint;
    price: bigint;
    location: string;
    contactPhone: string;
} {
    return {
        id: value.id,
        status: to_candid_ListingStatus_n41(_uploadFile, _downloadFile, value.status),
        title: value.title,
        contactName: value.contactName,
        propertyType: to_candid_PropertyType_n43(_uploadFile, _downloadFile, value.propertyType),
        bedrooms: value.bedrooms,
        owner: value.owner,
        area: value.area,
        description: value.description,
        listingType: to_candid_ListingType_n45(_uploadFile, _downloadFile, value.listingType),
        bathrooms: value.bathrooms,
        price: value.price,
        location: value.location,
        contactPhone: value.contactPhone
    };
}
function to_candid_record_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    foundationCost: bigint;
    projectName: string;
    projectType: ProjectType;
    owner: Principal;
    plumbingCost: bigint;
    totalArea: bigint;
    totalCost: bigint;
    flooringCost: bigint;
    finishingCost: bigint;
    roofingCost: bigint;
    notes: string;
    electricalCost: bigint;
    structureCost: bigint;
}): {
    id: string;
    foundationCost: bigint;
    projectName: string;
    projectType: _ProjectType;
    owner: Principal;
    plumbingCost: bigint;
    totalArea: bigint;
    totalCost: bigint;
    flooringCost: bigint;
    finishingCost: bigint;
    roofingCost: bigint;
    notes: string;
    electricalCost: bigint;
    structureCost: bigint;
} {
    return {
        id: value.id,
        foundationCost: value.foundationCost,
        projectName: value.projectName,
        projectType: to_candid_ProjectType_n32(_uploadFile, _downloadFile, value.projectType),
        owner: value.owner,
        plumbingCost: value.plumbingCost,
        totalArea: value.totalArea,
        totalCost: value.totalCost,
        flooringCost: value.flooringCost,
        finishingCost: value.finishingCost,
        roofingCost: value.roofingCost,
        notes: value.notes,
        electricalCost: value.electricalCost,
        structureCost: value.structureCost
    };
}
function to_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProjectType): {
    interior: null;
} | {
    commercial: null;
} | {
    residential: null;
} {
    return value == ProjectType.interior ? {
        interior: null
    } : value == ProjectType.commercial ? {
        commercial: null
    } : value == ProjectType.residential ? {
        residential: null
    } : value;
}
function to_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FloorStyle): {
    traditional: null;
} | {
    modern: null;
} | {
    contemporary: null;
} {
    return value == FloorStyle.traditional ? {
        traditional: null
    } : value == FloorStyle.modern ? {
        modern: null
    } : value == FloorStyle.contemporary ? {
        contemporary: null
    } : value;
}
function to_candid_variant_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ListingStatus): {
    rented: null;
} | {
    active: null;
} | {
    sold: null;
} {
    return value == ListingStatus.rented ? {
        rented: null
    } : value == ListingStatus.active ? {
        active: null
    } : value == ListingStatus.sold ? {
        sold: null
    } : value;
}
function to_candid_variant_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PropertyType): {
    commercial: null;
} | {
    plot: null;
} | {
    residential: null;
} {
    return value == PropertyType.commercial ? {
        commercial: null
    } : value == PropertyType.plot ? {
        plot: null
    } : value == PropertyType.residential ? {
        residential: null
    } : value;
}
function to_candid_variant_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ListingType): {
    buy: null;
} | {
    rent: null;
} | {
    sell: null;
} {
    return value == ListingType.buy ? {
        buy: null
    } : value == ListingType.rent ? {
        rent: null
    } : value == ListingType.sell ? {
        sell: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
